version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/basic
    steps:
      - checkout
      -
        run: 'sudo apt-get update && sudo apt-get install -y libpng-dev libjpeg62-turbo-dev && sudo apt-get install apache2 && sudo apt-get install mysql-server && sudo apt-get update apt-get install php5-mysql php5-mysql && sudo /etc/init.d/apache2 restart'
      -
        restore_cache:
          keys: ['v1-dependencies-{{ checksum "composer.json" }}', v1-dependencies-]
      -
        run: 'curl -sS https://getcomposer.org/installer | php'
      -
        save_cache:
          paths: [./vendor]
          key: 'v1-dependencies-{{ checksum "composer.json" }}'
      -
        run:
          name: 'Install awscli'
          command: "sudo apt install awsebcli --upgrade\n"
      -
        run:
          name: 'Create AWS credentials manually'
          command: "mkdir ~/.aws\ntouch ~/.aws/config\nchmod 600 ~/.aws/config\necho \"[profile eb-cli]\" > ~/.aws/config\necho \"aws_access_key_id=$AWS_ACCESS_KEY_ID\" >> ~/.aws/config\necho \"aws_secret_access_key=$AWS_SECRET_ACCESS_KEY\" >> ~/.aws/config\n"
      -
        run: 'vendor/bin/codecept run'
      -
        run:
          name: 'Deploy to EB if branch is Master'
          command: "eb use PhpYii-env --profile eb-cli\neb deploy -v --staged --profile eb-cli\n"
workflows:
  version: 2
  build-deploy:
    jobs:
      -
        deploy:
          filters: { branches: { only: [master, develop] } }