version: 2
jobs:
  build:
    docker:
      - image: tplatform/aws-linux-httpd24-php70
      - image: Cox-Automotive/aws-ebcli
          
    working_directory: ~/basic
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: curl -sS https://getcomposer.org/installer | php
      
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: vendor/bin/codecept run