var classes = [
    {
        "name": "app\\assets\\AppAsset",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "yii\\web\\AssetBundle"
        ],
        "parents": [
            "yii\\web\\AssetBundle"
        ],
        "lcom": 0,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 6,
        "loc": 15,
        "lloc": 9,
        "mi": 113.11,
        "mIwoC": 71.59,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "app\\widgets\\Alert",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "yii\\bootstrap\\Widget",
            "yii\\bootstrap\\Alert"
        ],
        "parents": [
            "yii\\bootstrap\\Widget"
        ],
        "lcom": 1,
        "length": 57,
        "vocabulary": 29,
        "volume": 276.9,
        "difficulty": 2.71,
        "effort": 750.84,
        "level": 0.37,
        "bugs": 0.09,
        "time": 42,
        "intelligentContent": 102.12,
        "number_operators": 10,
        "number_operands": 47,
        "number_operators_unique": 3,
        "number_operands_unique": 26,
        "cloc": 32,
        "loc": 53,
        "lloc": 21,
        "mi": 100.05,
        "mIwoC": 53.38,
        "commentWeight": 46.67,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "app\\controllers\\SiteController",
        "interface": false,
        "methods": [
            {
                "name": "behaviors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionIndex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionLogout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionContact",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionAbout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionSay",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionEntry",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "yii\\web\\Controller",
            "yii\\filters\\AccessControl",
            "yii\\filters\\VerbFilter",
            "app\\models\\LoginForm",
            "app\\models\\ContactForm",
            "app\\models\\EntryForm"
        ],
        "parents": [
            "yii\\web\\Controller"
        ],
        "lcom": 3,
        "length": 90,
        "vocabulary": 35,
        "volume": 461.64,
        "difficulty": 4.26,
        "effort": 1965.67,
        "level": 0.23,
        "bugs": 0.15,
        "time": 109,
        "intelligentContent": 108.41,
        "number_operators": 24,
        "number_operands": 66,
        "number_operators_unique": 4,
        "number_operands_unique": 31,
        "cloc": 31,
        "loc": 90,
        "lloc": 59,
        "mi": 81.49,
        "mIwoC": 42.04,
        "commentWeight": 39.45,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.94,
        "relativeSystemComplexity": 169.94,
        "totalStructuralComplexity": 1521,
        "totalDataComplexity": 8.43,
        "totalSystemComplexity": 1529.43,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "app\\controllers\\CountryController",
        "interface": false,
        "methods": [
            {
                "name": "actionIndex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\web\\Controller",
            "app\\models\\Country",
            "yii\\data\\Pagination"
        ],
        "parents": [
            "yii\\web\\Controller"
        ],
        "lcom": 1,
        "length": 21,
        "vocabulary": 11,
        "volume": 72.65,
        "difficulty": 1.89,
        "effort": 137.22,
        "level": 0.53,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 38.46,
        "number_operators": 4,
        "number_operands": 17,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 64.12,
        "mIwoC": 64.12,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 49.13,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "app\\commands\\HelloController",
        "interface": false,
        "methods": [
            {
                "name": "actionIndex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\console\\Controller"
        ],
        "parents": [
            "yii\\console\\Controller"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 1.33,
        "effort": 18.58,
        "level": 0.75,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 10.45,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 13,
        "loc": 22,
        "lloc": 9,
        "mi": 117.47,
        "mIwoC": 71.04,
        "commentWeight": 46.43,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "app\\models\\LoginForm",
        "interface": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validatePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "yii\\base\\Model",
            "app\\models\\User"
        ],
        "parents": [
            "yii\\base\\Model"
        ],
        "lcom": 2,
        "length": 43,
        "vocabulary": 21,
        "volume": 188.87,
        "difficulty": 5.8,
        "effort": 1095.44,
        "level": 0.17,
        "bugs": 0.06,
        "time": 61,
        "intelligentContent": 32.56,
        "number_operators": 14,
        "number_operands": 29,
        "number_operators_unique": 6,
        "number_operands_unique": 15,
        "cloc": 28,
        "loc": 67,
        "lloc": 39,
        "mi": 90.8,
        "mIwoC": 48.68,
        "commentWeight": 42.11,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.56,
        "relativeSystemComplexity": 49.56,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 2.25,
        "totalSystemComplexity": 198.25,
        "pageRank": 0.1,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "app\\models\\Country",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "yii\\db\\ActiveRecord"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.14,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "app\\models\\EntryForm",
        "interface": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\base\\Model"
        ],
        "parents": [
            "yii\\base\\Model"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0.83,
        "effort": 10,
        "level": 1.2,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 14.4,
        "number_operators": 1,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 70.5,
        "mIwoC": 70.5,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "pageRank": 0.1,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "app\\models\\User",
        "interface": false,
        "methods": [
            {
                "name": "findIdentity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findIdentityByAccessToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findByUsername",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAuthKey",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateAuthKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validatePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "yii\\base\\BaseObject",
            "yii\\web\\IdentityInterface",
            "static",
            "static",
            "static"
        ],
        "parents": [
            "yii\\base\\BaseObject"
        ],
        "lcom": 4,
        "length": 62,
        "vocabulary": 21,
        "volume": 272.32,
        "difficulty": 3.92,
        "effort": 1066.6,
        "level": 0.26,
        "bugs": 0.09,
        "time": 59,
        "intelligentContent": 69.53,
        "number_operators": 15,
        "number_operands": 47,
        "number_operators_unique": 3,
        "number_operands_unique": 18,
        "cloc": 27,
        "loc": 75,
        "lloc": 48,
        "mi": 85.67,
        "mIwoC": 45.6,
        "commentWeight": 40.07,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 9.86,
        "relativeSystemComplexity": 9.86,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 69,
        "totalSystemComplexity": 69,
        "pageRank": 0.24,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "app\\models\\ContactForm",
        "interface": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "contact",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "yii\\base\\Model"
        ],
        "parents": [
            "yii\\base\\Model"
        ],
        "lcom": 3,
        "length": 23,
        "vocabulary": 11,
        "volume": 79.57,
        "difficulty": 2,
        "effort": 159.13,
        "level": 0.5,
        "bugs": 0.03,
        "time": 9,
        "intelligentContent": 39.78,
        "number_operators": 5,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 17,
        "loc": 46,
        "lloc": 29,
        "mi": 94.95,
        "mIwoC": 54.52,
        "commentWeight": 40.43,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.54,
        "relativeSystemComplexity": 49.54,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 1.63,
        "totalSystemComplexity": 148.63,
        "pageRank": 0.1,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]